dependencies:
  - yarn.lock

gh-actions:
  - .github/workflows/**/*

test:
  - src/tests/**/*

components:
  - src/components/**/*

ts-types:
  - src/types/**/*

documentation:
  - any: ["README.md", "CODE_OF_CONDUCT.md"]
