name: "Run test cases"
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run-tests:
    name: Running tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run test cases
        run: yarn install && yarn test:coverage
